workflows:
  ios-development:
    name: iOS Development & Testing
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          
    scripts:
      - name: Install system dependencies
        script: |
          # Install SQLite if needed
          brew install sqlite3 || true
          
      - name: Get Flutter packages
        script: |
          cd cipher_app
          flutter packages pub get
          
      - name: Analyze code
        script: |
          cd cipher_app
          flutter analyze
          
      - name: Build iOS (debug)
        script: |
          cd cipher_app
          flutter build ios --debug --no-codesign
          
      - name: Start iOS Simulator
        script: |
          # This will be available in Codemagic's iOS Simulator
          echo "iOS Simulator ready for testing"
          
    artifacts:
      - cipher_app/build/ios/iphoneos/*.app
      
    publishing:
      # Enable iOS Simulator access
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID