workflows:
  flutter-ios-development:
    name: iOS Development & Testing
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd cipher_app
          flutter pub get
          
      - name: Build iOS for Simulator
        script: |
          cd cipher_app
          flutter build ios --simulator --debug

    artifacts:
      - cipher_app/build/ios/iphonesimulator/Runner.app