# Codemagic detectará automaticamente, mas você pode customizar
workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter packages get
      - name: Build iOS
        script: cd cipher_app || flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app