name: cipher_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  carousel_slider_plus: ^7.1.1
  flutter_staggered_grid_view: ^0.6.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0  # For desktop support
  path: ^1.8.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/data/

  fonts:
    - family: Asimovian
      fonts:
        - asset: assets/fonts/Asimovian-Regular.ttf