name: cipher_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  carousel_slider_plus: ^7.1.1
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0  # For desktop support
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.2
  flutter_speed_dial: ^7.0.0
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  firebase_analytics: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/logos/
    - assets/graphics/

  fonts:
    - family: Asimovian
      fonts:
        - asset: assets/fonts/Asimovian-Regular.ttf
          weight: 400

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth_wght.ttf
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth_wght.ttf
          style: italic

    - family: Atkinson
      fonts:
        - asset: assets/fonts/AtkinsonHyperlegible-Regular.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-Bold.ttf
          weight: 700
        - asset: assets/fonts/AtkinsonHyperlegible-Italic.ttf
          style: italic
        - asset: assets/fonts/AtkinsonHyperlegible-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf