// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWewT7qIfm24LIUNozdyP1BMmtaVoVV1g',
    appId: '1:626503496187:web:12d88396c72b1c7870db5e',
    messagingSenderId: '626503496187',
    projectId: 'cipherapp-8c2ee',
    authDomain: 'cipherapp-8c2ee.firebaseapp.com',
    storageBucket: 'cipherapp-8c2ee.firebasestorage.app',
    measurementId: 'G-PMWJPW8PTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlb5ok06zm1yIW5KcqqtiQk59yCFvM2jQ',
    appId: '1:626503496187:android:191ccca7f6cfb78c70db5e',
    messagingSenderId: '626503496187',
    projectId: 'cipherapp-8c2ee',
    storageBucket: 'cipherapp-8c2ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_RPRjXXa86lmFsiQ7nj2jSx_yPAQV110',
    appId: '1:626503496187:ios:aea6925f495bfa0e70db5e',
    messagingSenderId: '626503496187',
    projectId: 'cipherapp-8c2ee',
    storageBucket: 'cipherapp-8c2ee.firebasestorage.app',
    androidClientId:
        '626503496187-97o5d9ki4dpeou4712al5f18lpohn0ke.apps.googleusercontent.com',
    iosClientId:
        '626503496187-pneti15mm653acbbaqinq5n4bqib0qkb.apps.googleusercontent.com',
    iosBundleId: 'com.newHeartBrasil.cordis',
  );
}
