// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWewT7qIfm24LIUNozdyP1BMmtaVoVV1g',
    appId: '1:626503496187:web:be79bdccf08839ac70db5e',
    messagingSenderId: '626503496187',
    projectId: 'cipherapp-8c2ee',
    authDomain: 'cipherapp-8c2ee.firebaseapp.com',
    storageBucket: 'cipherapp-8c2ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlb5ok06zm1yIW5KcqqtiQk59yCFvM2jQ',
    appId: '1:626503496187:android:6c8883ac416779ff70db5e',
    messagingSenderId: '626503496187',
    projectId: 'cipherapp-8c2ee',
    storageBucket: 'cipherapp-8c2ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuqESM-VBOIEXSpQnKBvZCbLC8oKkwL48',
    appId: '1:626503496187:ios:0d6603fcaf14b0a970db5e',
    messagingSenderId: '626503496187',
    projectId: 'cipherapp-8c2ee',
    storageBucket: 'cipherapp-8c2ee.firebasestorage.app',
    iosBundleId: 'com.example.cipherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuqESM-VBOIEXSpQnKBvZCbLC8oKkwL48',
    appId: '1:626503496187:ios:0d6603fcaf14b0a970db5e',
    messagingSenderId: '626503496187',
    projectId: 'cipherapp-8c2ee',
    storageBucket: 'cipherapp-8c2ee.firebasestorage.app',
    iosBundleId: 'com.example.cipherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWewT7qIfm24LIUNozdyP1BMmtaVoVV1g',
    appId: '1:626503496187:web:59007bed61b7f6b670db5e',
    messagingSenderId: '626503496187',
    projectId: 'cipherapp-8c2ee',
    authDomain: 'cipherapp-8c2ee.firebaseapp.com',
    storageBucket: 'cipherapp-8c2ee.firebasestorage.app',
  );
}
